'use client';
import {bounded,drawingMotions,motionsFor,type DrawingMotion,type DrawingWeather} from '@/lib/drawing-project';
import type {useDrawingEditor} from './use-drawing-editor';
const symbols:Record<DrawingMotion,string>={still:'Ⅱ',move:'→',hop:'↑',sway:'∿',float:'↝',swim:'≈',bounce:'↟'};
export function DrawingControls({e}:{e:ReturnType<typeof useDrawingEditor>}){
 const disabled=!e.loaded||e.busy||e.playing;
 function motion(id:DrawingMotion){e.patchItem({motion:id});e.setDestination(false);}
 return <aside className="draw-controls" id="drawing-actions"><div className="draw-section-title"><small>MAKE IT MOVE</small><h2><span className="story-section-number green">3</span> 어떻게 움직일까?</h2></div>
 {e.selected&&e.selectedAsset?<><div className="story-selected"><img src={e.selectedAsset.source} alt="선택한 그림"/><strong>{e.selectedAsset.name}</strong></div><div className="draw-motion-grid">{drawingMotions.filter(m=>motionsFor(e.selectedAsset!.kind).includes(m.id)).map(m=><button type="button" className={`story-motion motion-${m.id}`} key={m.id} disabled={disabled} aria-pressed={e.selected!.motion===m.id} onClick={()=>motion(m.id)}><span aria-hidden="true">{symbols[m.id]}</span>{m.label}</button>)}</div><p className="draw-help">{drawingMotions.find(m=>m.id===e.selected!.motion)?.description}</p>
 <button type="button" className="draw-destination" aria-pressed={e.destination} disabled={disabled} onClick={()=>{e.stop();e.setDestination(!e.destination);}}>◎ 도착할 곳 고르기</button><div className="draw-pair"><button type="button" disabled={disabled} onClick={()=>e.patchItem({motion:e.selected!.motion==='still'?'move':e.selected!.motion,target:{x:20,y:e.selected!.y}})}>← 왼쪽으로</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({motion:e.selected!.motion==='still'?'move':e.selected!.motion,target:{x:80,y:e.selected!.y}})}>오른쪽으로 →</button></div>{e.selected.target?<button type="button" className="draw-text-button" disabled={disabled} onClick={()=>{e.patchItem({target:undefined});e.setDestination(false);}}>이동 경로 지우기</button>:null}
 <fieldset><legend>빠르기</legend><div className="draw-trio">{([['slow','천천히'],['normal','보통'],['fast','빠르게']] as const).map(([id,label])=><button type="button" key={id} disabled={disabled} aria-pressed={e.selected!.speed===id} onClick={()=>e.patchItem({speed:id})}>{label}</button>)}</div></fieldset>
 <fieldset><legend>크기와 방향</legend><div className="draw-trio"><button type="button" disabled={disabled} onClick={()=>e.patchItem({width:bounded(e.selected!.width-3,5,65)})}>작게</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({width:bounded(e.selected!.width+3,5,65)})}>크게</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({flipped:!e.selected!.flipped})}>뒤집기</button></div></fieldset>
 <label>무슨 말을 할까요?<textarea aria-label="이 그림의 대사" disabled={disabled} maxLength={80} value={e.selected.speech} onChange={event=>e.patchItem({speech:event.target.value})} placeholder="예: 우리 같이 놀자!"/></label>
 <details><summary>위치·겹침·복사</summary><div className="draw-pair"><button type="button" disabled={disabled} onClick={()=>e.patchItem({x:bounded(e.selected!.x-3,2,98)})}>위치 ←</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({x:bounded(e.selected!.x+3,2,98)})}>위치 →</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({y:bounded(e.selected!.y-3,5,98)})}>위치 ↑</button><button type="button" disabled={disabled} onClick={()=>e.patchItem({y:bounded(e.selected!.y+3,5,98)})}>위치 ↓</button><button type="button" disabled={disabled} onClick={()=>e.layer(-1)}>뒤로</button><button type="button" disabled={disabled} onClick={()=>e.layer(1)}>앞으로</button><button type="button" disabled={disabled} onClick={e.duplicate}>그림 복사</button><button type="button" disabled={disabled} onClick={e.remove}>무대에서 지우기</button></div></details></>:<div className="story-action-empty"><span aria-hidden="true">↖</span><strong>내 그림을 톡 눌러요</strong><p>움직임과 대사를 정할 수 있어요.</p></div>}
 <section className="draw-weather"><h3>분위기도 바꿔 봐요</h3><div className="draw-weather-grid">{([['none','없음'],['wind','바람'],['rain','비'],['snow','눈']] as [DrawingWeather,string][]).map(([id,label])=><button type="button" key={id} className={`weather-${id}`} disabled={disabled} aria-pressed={e.scene.weather===id} onClick={()=>e.editScene({weather:id})}><span aria-hidden="true">{id==='none'?'○':id==='wind'?'∿':id==='rain'?'⋮':'❄'}</span>{label}</button>)}</div>
 {e.scene.weather!=='none'?<><div className="draw-pair"><button type="button" disabled={disabled} aria-pressed={e.scene.strength==='gentle'} onClick={()=>e.editScene({strength:'gentle'})}>살살</button><button type="button" disabled={disabled} aria-pressed={e.scene.strength==='strong'} onClick={()=>e.editScene({strength:'strong'})}>세게</button></div><div className="draw-pair"><button type="button" disabled={disabled} aria-pressed={e.scene.wind==='left'} onClick={()=>e.editScene({wind:'left'})}>← 방향</button><button type="button" disabled={disabled} aria-pressed={e.scene.wind==='right'} onClick={()=>e.editScene({wind:'right'})}>방향 →</button></div><p className="draw-help">재생하면 효과가 움직여요. 바람은 식물도 흔들어요.</p></>:null}</section>
 </aside>;
}
