'use client';
import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {drawingId,drawingKinds,type DrawingAsset,type DrawingKind} from '@/lib/drawing-project';
import {prepareRaster,readDrawingImage} from '@/lib/drawing-media';
type Pending={original:string;name:string;revision:number};
type Props={assets:DrawingAsset[];disabled:boolean;onPlace:(asset:DrawingAsset,isNew?:boolean)=>boolean;onError:(text:string)=>void};
export function DrawingLibrary({assets,disabled,onPlace,onError}:Props){
  const picker=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),sequence=useRef(0);
  const [pending,setPending]=useState<Pending|null>(null),[kind,setKind]=useState<DrawingKind>('animal'),[removePaper,setRemovePaper]=useState(false),[trim,setTrim]=useState(true),[busy,setBusy]=useState(false);
  const [preview,setPreview]=useState<{source:string;width:number;height:number}|null>(null),[message,setMessage]=useState('');
  async function pick(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;const job=++sequence.current;setBusy(true);setMessage('');try{const image=await readDrawingImage(file);if(job!==sequence.current)return;setRemovePaper(false);setTrim(true);setPending({original:image.source,name:file.name.replace(/\.[^.]+$/,'').slice(0,40)||'내 그림',revision:job});}catch(cause){if(job===sequence.current){onError(cause instanceof Error?cause.message:'그림을 읽지 못했어요.');setBusy(false);}}}
  useEffect(()=>{if(!pending)return;let canceled=false;setBusy(true);setPreview(null);setMessage('');void prepareRaster(pending.original,removePaper,trim&&kind!=='background').then(image=>{if(!canceled)setPreview(image);}).catch(cause=>{if(!canceled)setMessage(cause instanceof Error?cause.message:'그림을 확인해 주세요.');}).finally(()=>{if(!canceled)setBusy(false);});return()=>{canceled=true;};},[pending?.revision,pending?.original,removePaper,trim,kind]);
  function add(){if(!pending||!preview||busy)return;const asset:DrawingAsset={...preview,id:drawingId('asset'),name:pending.name.trim()||'내 그림',kind};if(onPlace(asset,true)){setPending(null);setPreview(null);}}
  return <aside className="draw-library"><div className="draw-section-title"><small>01 / MY DRAWING</small><h2>내 그림</h2></div>
    <input type="file" ref={picker} accept="image/png,image/jpeg,image/webp" aria-label="그림 파일 선택" hidden onChange={event=>void pick(event)}/><input type="file" ref={camera} accept="image/*" capture="environment" aria-label="그림 사진 촬영" hidden onChange={event=>void pick(event)}/>
    <div className="draw-upload-actions"><button type="button" className="draw-primary" disabled={disabled||busy||assets.length>=12} onClick={()=>picker.current?.click()}>＋ 그림 고르기</button><button type="button" disabled={disabled||busy||assets.length>=12} onClick={()=>camera.current?.click()}>사진 찍기</button></div><p className="draw-help">그림 한 장이면 돼요. JPG · PNG · WebP / 10MB 이하</p>
    {pending?<section className="draw-upload-review" aria-label="올릴 그림 확인"><div className="draw-checker">{preview?<img src={preview.source} alt="등록할 내 그림 미리보기"/>:<span>{busy?'그림 준비 중':'설정을 확인해 주세요'}</span>}</div><label>그림 이름<input value={pending.name} maxLength={40} onChange={e=>setPending({...pending,name:e.target.value})}/></label><fieldset><legend>무엇을 그렸나요?</legend><div className="draw-kind-buttons">{drawingKinds.map(k=><button type="button" key={k.id} aria-pressed={kind===k.id} onClick={()=>setKind(k.id)}>{k.label}</button>)}</div></fieldset><label className="draw-check"><input type="checkbox" checked={removePaper} onChange={e=>setRemovePaper(e.target.checked)}/>흰 종이 지우기</label><p className="draw-help">밝은 그림까지 지워지면 꺼 주세요. 복잡한 배경을 자동으로 지우는 기능은 아니에요.</p>{kind!=='background'?<label className="draw-check"><input type="checkbox" checked={trim} onChange={e=>setTrim(e.target.checked)}/>투명한 여백 줄이기</label>:null}{message?<p role="alert" className="draw-error">{message}</p>:null}<div className="draw-pair"><button type="button" disabled={busy} onClick={()=>{sequence.current++;setPending(null);setPreview(null);}}>취소</button><button type="button" className="draw-primary" disabled={busy||!preview||disabled} onClick={add}>{busy?'준비 중':kind==='background'?'배경으로 쓰기':'무대에 놓기'}</button></div></section>:null}
    <div className="draw-library-title"><strong>내 보관함</strong><small>{assets.length}/12</small></div><div className="draw-asset-grid">{assets.map(a=><button type="button" key={a.id} disabled={disabled} className="draw-asset" onClick={()=>onPlace(a)} aria-label={`${a.name} 다시 놓기`}><span className="draw-checker"><img src={a.source} alt=""/></span><strong>{a.name}</strong><small>{drawingKinds.find(k=>k.id===a.kind)?.label}</small></button>)}</div>{!assets.length&&!pending?<p className="draw-empty-help">내가 그린 강아지, 꽃, 구름을 올려 보세요. 기본 캐릭터로 바뀌지 않아요.</p>:null}<p className="draw-privacy">그림은 외부 서버에 보내지 않고 이 브라우저에서 처리해요.</p>
  </aside>;
}
