from __future__ import annotations

import argparse
import base64
from pathlib import Path

from PIL import Image, ImageOps


WORK_IDS = ("heungbu", "chunhyang", "honggildong", "simcheong", "byeoljubu", "jeonwoochi")


def cell(image: Image.Image, columns: int, rows: int, index: int, inset: float = 0) -> Image.Image:
    column = index % columns
    row = index // columns
    left = round(image.width * column / columns)
    top = round(image.height * row / rows)
    right = round(image.width * (column + 1) / columns)
    bottom = round(image.height * (row + 1) / rows)
    inset_x = round((right - left) * inset)
    inset_y = round((bottom - top) * inset)
    return image.crop((left + inset_x, top + inset_y, right - inset_x, bottom - inset_y))


def save_webp(image: Image.Image, output: Path, size: tuple[int, int], fit: bool = False) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    processed = ImageOps.fit(image, size, method=Image.Resampling.LANCZOS) if fit else ImageOps.contain(image, size, method=Image.Resampling.LANCZOS)
    if not fit:
        canvas = Image.new("RGBA", size, (0, 0, 0, 0))
        canvas.alpha_composite(processed.convert("RGBA"), ((size[0] - processed.width) // 2, (size[1] - processed.height) // 2))
        processed = canvas
    processed.save(output, "WEBP", quality=84, method=6)


def process_characters(atlas: Path, works: tuple[str, str, str], output_root: Path) -> None:
    with Image.open(atlas).convert("RGBA") as image:
        for index in range(9):
            work = works[index // 3]
            character_number = index % 3 + 1
            save_webp(cell(image, 3, 3, index, inset=0.065), output_root / "classics" / work / "characters" / f"character-{character_number:02d}.webp", (512, 512))


def process_backgrounds(atlas: Path, output_root: Path, scene_number: int = 1) -> None:
    with Image.open(atlas).convert("RGB") as image:
        for index, work in enumerate(WORK_IDS):
            save_webp(cell(image, 3, 2, index), output_root / "classics" / work / "backgrounds" / f"scene-{scene_number:02d}.webp", (960, 540), fit=True)


def process_props(atlas: Path, output_root: Path) -> None:
    outputs = (
        ("buildings", "gate.webp"),
        ("buildings", "thatched-house.webp"),
        ("buildings", "government-hall.webp"),
        ("nature", "pine-tree.webp"),
        ("nature", "rock.webp"),
        ("props", "wooden-table.webp"),
        ("props", "folding-screen.webp"),
        ("props", "rice-bowl.webp"),
        ("props", "royal-scroll.webp"),
        ("props", "magic-fan.webp"),
        ("animals", "spotted-dog.webp"),
        ("effects", "magic-wind.webp"),
    )
    with Image.open(atlas).convert("RGBA") as image:
        for index, (category, filename) in enumerate(outputs):
            save_webp(cell(image, 4, 3, index), output_root / "shared" / category / filename, (512, 512))


def process_props_extra(atlas: Path, output_root: Path) -> None:
    outputs = (
        ("buildings", "prison-bars.webp"),
        ("buildings", "royal-throne.webp"),
        ("props", "wooden-boat.webp"),
        ("buildings", "market-stall.webp"),
        ("props", "rice-sack.webp"),
        ("props", "treasure-chest.webp"),
        ("props", "water-jar.webp"),
        ("props", "paper-lantern.webp"),
        ("props", "rope-coil.webp"),
        ("props", "joseon-sword.webp"),
        ("props", "buk-drum.webp"),
        ("animals", "magpie.webp"),
    )
    with Image.open(atlas).convert("RGBA") as image:
        for index, (category, filename) in enumerate(outputs):
            save_webp(cell(image, 4, 3, index), output_root / "shared" / category / filename, (512, 512))


def write_typescript_bundle(output_root: Path, ts_output: Path) -> None:
    rows = [
        "// Generated by scripts/process-generated-atlases.py. Do not edit by hand.\n",
        "export const STAGE_ASSET_IMAGE_DATA: Record<string, string> = {\n",
    ]
    for image_path in sorted(output_root.rglob("*.webp")):
        key = image_path.relative_to(output_root).as_posix()
        encoded = base64.b64encode(image_path.read_bytes()).decode("ascii")
        rows.append(f'  "{key}": "{encoded}",\n')
    rows.append("};\n")
    ts_output.parent.mkdir(parents=True, exist_ok=True)
    ts_output.write_text("".join(rows), encoding="utf-8", newline="\n")


def write_typescript_bundle_parts(output_root: Path, ts_output_dir: Path) -> None:
    groups: dict[str, list[Path]] = {}
    for image_path in sorted(output_root.rglob("*.webp")):
        relative = image_path.relative_to(output_root)
        group = relative.parts[1] if relative.parts[0] == "classics" else relative.parts[0]
        groups.setdefault(group.replace("-", "_"), []).append(image_path)

    ts_output_dir.mkdir(parents=True, exist_ok=True)
    imports: list[str] = []
    names: list[str] = []
    for group, image_paths in groups.items():
        variable = f"imageData_{group}"
        names.append(variable)
        imports.append(f'import {{ {variable} }} from "./{group}.generated";\n')
        rows = [f"export const {variable}: Record<string, string> = {{\n"]
        for image_path in image_paths:
            key = image_path.relative_to(output_root).as_posix()
            encoded = base64.b64encode(image_path.read_bytes()).decode("ascii")
            rows.append(f'  "{key}": "{encoded}",\n')
        rows.append("};\n")
        (ts_output_dir / f"{group}.generated.ts").write_text("".join(rows), encoding="utf-8", newline="\n")

    index_rows = ["// Generated image bundle index.\n", *imports, "\nexport const STAGE_ASSET_IMAGE_DATA: Record<string, string> = Object.assign({},\n"]
    index_rows.extend(f"  {name},\n" for name in names)
    index_rows.append(");\n")
    (ts_output_dir / "index.ts").write_text("".join(index_rows), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--characters-a", type=Path, required=True)
    parser.add_argument("--characters-b", type=Path, required=True)
    parser.add_argument("--backgrounds", type=Path, required=True)
    parser.add_argument("--backgrounds-b", type=Path)
    parser.add_argument("--backgrounds-c", type=Path)
    parser.add_argument("--props", type=Path, required=True)
    parser.add_argument("--props-extra", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--ts-output", type=Path)
    args = parser.parse_args()

    print("Processing character atlas A...", flush=True)
    process_characters(args.characters_a, WORK_IDS[:3], args.output)
    print("Processing character atlas B...", flush=True)
    process_characters(args.characters_b, WORK_IDS[3:], args.output)
    print("Processing background atlas 1...", flush=True)
    process_backgrounds(args.backgrounds, args.output, 1)
    if args.backgrounds_b:
        print("Processing background atlas 2...", flush=True)
        process_backgrounds(args.backgrounds_b, args.output, 2)
    if args.backgrounds_c:
        print("Processing background atlas 3...", flush=True)
        process_backgrounds(args.backgrounds_c, args.output, 3)
    print("Processing prop atlas 1...", flush=True)
    process_props(args.props, args.output)
    if args.props_extra:
        print("Processing prop atlas 2...", flush=True)
        process_props_extra(args.props_extra, args.output)
    if args.ts_output:
        print("Writing TypeScript image bundle...", flush=True)
        write_typescript_bundle(args.output, args.ts_output)
    print("Done.", flush=True)


if __name__ == "__main__":
    main()
